import { z } from "zod";
import { tokenBehaviorInsightSchema } from "../wallet/schemas";

/**
 * Schema for a single social media post generated by the LLM.
 */
export const socialPostSchema = z.object({
  platform: z.enum(["threads", "x", "linkedin"]),
  content: z.string().min(1),
});

/**
 * Schema for the LLM output containing all three platform posts.
 * This is what we expect DeepSeek to return as structured JSON.
 */
export const llmSocialPostsOutputSchema = z.object({
  threads: z.string().min(1),
  x: z.string().min(1).max(280),
  linkedin: z.string().min(1),
});

/**
 * Schema for the full API response returned to the frontend.
 */
export const socialPostsResponseSchema = z.object({
  threads: socialPostSchema,
  x: socialPostSchema,
  linkedin: socialPostSchema,
});

/**
 * Schema for the request body of POST /api/social/generate.
 * Accepts the token analysis data and basic token metadata.
 */
export const generateSocialPostsRequestSchema = z.object({
  tokenAnalysis: tokenBehaviorInsightSchema,
  tokenAddress: z.string().regex(
    /^0x[a-fA-F0-9]{40}$/,
    "Invalid token contract address"
  ),
  tokenSymbol: z.string().min(1).max(20).optional(),
});
